import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TopBar from "@/components/base/TopBar";
import BottomBar from "@/components/base/BottomBar";
import { ThemeProvider } from "@/provider/ThemeProvider";
import AuthProvider from "@/provider/AuthProvider";
import { SWRProvider } from "@/provider/SwrProvider";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
    subsets: ["latin"], // 必要なサブセットを指定
    weight: ["100", "200", "300", "400", "500", "600", "700"], // 必要なウェイトを指定
});

const baseStyle = "w-screen h-screen flex justify-center items-center bg-background overflow-hidden";
const responsiveStyle = "max-w-3xl w-full h-full  py-[70px]  px-5 overflow-y-scroll hidden-scrollbar";

export const metadata: Metadata = {
    title: "Anki",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className + " " + baseStyle}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <AuthProvider>
                        {/* <SWRProvider> */}
                        <TopBar />
                        <div className={responsiveStyle}>{children}</div>
                        <BottomBar />
                        <Toaster />
                        {/* </SWRProvider> */}
                    </AuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
